version: '3'


services:
  server:
    image: cartoonizer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  client:
    image: frontend
    ports: 
      - "3001:3001"